# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Authz0 < Formula
  desc "Authz0 is an automated authorization test tool. Unauthorized access can be identified based on URLs and Roles & Credentials."
  homepage "https://www.hahwul.com"
  version "1.1.2"

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/hahwul/authz0/releases/download/v1.1.2/authz0_1.1.2_darwin_arm64.tar.gz"
      sha256 "1dd377f1fa2a0883dc9a7590b86a50568653e4ac5b8fab4f7a5eeeab8f81e465"

      def install
        bin.install "authz0"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/hahwul/authz0/releases/download/v1.1.2/authz0_1.1.2_darwin_amd64.tar.gz"
      sha256 "f87e51443b0d70ccbbc41064cddfe7ece987f97178f53d3c98c59622eb307dec"

      def install
        bin.install "authz0"
      end
    end
  end

  on_linux do
    if Hardware::CPU.arm? && !Hardware::CPU.is_64_bit?
      url "https://github.com/hahwul/authz0/releases/download/v1.1.2/authz0_1.1.2_linux_armv6.tar.gz"
      sha256 "87775248cb911955e65a661c55ea76785b5f047e97f603f92a35ab7b2fa41b3e"

      def install
        bin.install "authz0"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/hahwul/authz0/releases/download/v1.1.2/authz0_1.1.2_linux_arm64.tar.gz"
      sha256 "489ff4a7a8e99eaa65e02cfd0713b31dcef64e1cd5962895b022cfc0fd6e9fc6"

      def install
        bin.install "authz0"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/hahwul/authz0/releases/download/v1.1.2/authz0_1.1.2_linux_amd64.tar.gz"
      sha256 "ee763a064daa922b87e3c8f61f5f7f5d0d5995606760457b9688511b95b3f303"

      def install
        bin.install "authz0"
      end
    end
  end

  test do
    system "#{bin}/authz0 version"
  end
end
