# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Authz0 < Formula
  desc "Authz0 is an automated authorization test tool. Unauthorized access can be identified based on URLs and Roles & Credentials."
  homepage "https://www.hahwul.com"
  version "1.1.1"

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/hahwul/authz0/releases/download/v1.1.1/authz0_1.1.1_darwin_arm64.tar.gz"
      sha256 "9cfae7d19cfdbffe3ca4efe1b45a3e6d346ed0a4c2a731ecb37c876c49bbdd5d"

      def install
        bin.install "authz0"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/hahwul/authz0/releases/download/v1.1.1/authz0_1.1.1_darwin_amd64.tar.gz"
      sha256 "b5f7e9705b7b03086e0a792806e29e777d6ebe5812e6b1e9a5999052c7f53575"

      def install
        bin.install "authz0"
      end
    end
  end

  on_linux do
    if Hardware::CPU.arm? && !Hardware::CPU.is_64_bit?
      url "https://github.com/hahwul/authz0/releases/download/v1.1.1/authz0_1.1.1_linux_armv6.tar.gz"
      sha256 "a45ff29cbe160e869aa937be49077356fa969719d821e3d38fdc45356490c286"

      def install
        bin.install "authz0"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/hahwul/authz0/releases/download/v1.1.1/authz0_1.1.1_linux_arm64.tar.gz"
      sha256 "b4b23b220641d1ecdb49cc98ece7ad93e310870bb4597517b73c6c21cb38264c"

      def install
        bin.install "authz0"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/hahwul/authz0/releases/download/v1.1.1/authz0_1.1.1_linux_amd64.tar.gz"
      sha256 "cbe99b83989de5089d253e8cb0765c1298c5f84b3a7d0aad437f64d37ec5f236"

      def install
        bin.install "authz0"
      end
    end
  end

  test do
    system "#{bin}/authz0 version"
  end
end
